name: BRISA Helpdesk
services:
  rdbms:
    container_name: brisa-helpdesk-database
    image: 'postgres:17.6'
    environment:
      - 'POSTGRES_DB=helpdesk'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
